version: '3'

services:
  test:
    build: .
    command: sh -c 'bundle exec rspec'
    volumes:
      - .:/app/
      - bundler_gems:/usr/local/bundle/
    environment:
      RAILS_ENV: 'test'
    ports:
      - 3000:3000

volumes:
  bundler_gems: