module CamaleonCms
  module Frontend
    module SeoHelper
      # add seo attributes to your page
      # you can pass custom data to overwrite default data generated by the system
      # return hash of seo attributes used by the_head(...)
      def cama_the_seo(data = {})
        visited_post = camaleon_frontend_visited_state(:frontend_visited_post, :@cama_visited_post)
        visited_post_type = camaleon_frontend_visited_state(:frontend_visited_post_type, :@cama_visited_post_type)
        visited_tag = camaleon_frontend_visited_state(:frontend_visited_tag, :@cama_visited_tag)
        visited_category = camaleon_frontend_visited_state(:frontend_visited_category, :@cama_visited_category)
        visited_user = CurrentRequest.frontend_user
        visited_user = instance_variable_get(:@user) if visited_user.nil? && instance_variable_defined?(:@user)
        CurrentRequest.frontend_user = visited_user if CurrentRequest.frontend_user.nil? && visited_user.present?

        data2 = if is_home?
                  {}
                elsif is_page?
                  { image: visited_post.the_thumb_url,
                    title: "#{current_site.the_title} | #{visited_post.the_title}",
                    description: visited_post.the_excerpt,
                    keywords: visited_post.the_keywords,
                    object: visited_post }
                elsif is_ajax?
                  {}
                elsif is_search?
                  { title: "#{current_site.the_title} | #{ct('search_title', default: 'Search')}" }
                elsif is_post_type?
                  { image: visited_post_type.the_thumb_url,
                    title: "#{current_site.the_title} | #{visited_post_type.the_title}",
                    description: visited_post_type.the_excerpt,
                    keywords: visited_post_type.the_keywords,
                    object: visited_post_type }
                elsif is_post_tag?
                  { title: "#{current_site.the_title} | #{visited_tag.the_title}",
                    description: visited_tag.the_excerpt,
                    keywords: visited_tag.the_keywords,
                    object: visited_tag }
                elsif is_category?
                  { image: visited_category.the_thumb_url,
                    title: "#{current_site.the_title} | #{visited_category.the_title}",
                    description: visited_category.the_excerpt,
                    keywords: visited_category.the_keywords,
                    object: visited_category }
                elsif is_profile?
                  { image: visited_user.the_avatar, title: "#{current_site.the_title} | #{visited_user.the_name}",
                    description: visited_user.the_slogan, object: visited_user }
                else
                  {}
                end
        cama_build_seo(data2.merge!(camaleon_frontend_seo_settings || {}).merge(data))
      end

      # permit to define seo attributes by code without hooks
      # (check here for more attributes: https://github.com/kpumuk/meta-tags)
      # @Sample:
      # cama_seo_settings(
      #   {title: "my custom title", description: "my descr", keywords: "my keywords", image: 'my img url'}
      # )
      # This values will be shown within the_head(...)
      def cama_seo_settings(options)
        CurrentRequest.frontend_seo_settings ||= {}
        CurrentRequest.frontend_seo_settings = CurrentRequest.frontend_seo_settings.merge(options)
      end

      private

      def camaleon_frontend_seo_settings
        CurrentRequest.frontend_seo_settings
      end

      # create seo attributes with options + default attributes
      def cama_build_seo(options = {})
        options[:image] = current_site.get_option('screenshot', current_site.the_logo) if options[:image].blank?
        options[:title] = current_site.the_title if options[:title].blank?
        options[:description] = current_site.the_option('seo_description') if options[:description].blank?
        options[:url] = request.original_url
        options[:keywords] = current_site.the_option('keywords') if options[:keywords].blank?

        s = {
          keywords: options[:keywords],
          author: current_site.get_option('seo_author'),
          icon: current_site.the_icon,
          og: {
            title: options[:title],
            description: options[:description],
            type: 'website',
            url: options[:url],
            image: options[:image]
          },
          twitter: {
            card: 'summary',
            title: options[:title],
            description: options[:description],
            url: options[:url],
            image: options[:image],
            site: current_site.get_option('twitter_card'),
            creator: current_site.get_option('twitter_card'),
            domain: request.host
          },
          alternate: [
            { type: 'application/rss+xml', href: cama_rss_url }
          ],
          canonical: current_site.get_option('seo_canonical')&.translate
        }.merge!(options.except(:object))

        object_option = options[:object]
        l = current_site.get_languages
        if l.size > 1
          l.each do |lang|
            s[:alternate] << {
              href: object_option.present? ? object_option.the_url(locale: lang) : current_site.the_url(locale: lang),
              hreflang: lang
            }
          end
        end

        # call all hooks for seo
        r = { seo_data: s, object: object_option }
        hooks_run('seo', r)
        r[:seo_data]
      end
    end
  end
end
