name: Test supported versions
on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_6_1.gemfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1

      - name: Run Rubocop
        run: bundle exec rubocop
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JS modules
        run: yarn
      - name: Run ESLint
        run: yarn eslint . --ext .js,.jsx,.ts,.tsx
  spec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, "3.0"]
        gemfile: [rails_6_0, rails_6_1, rails_7_0]
        include:
          # Rails < 7.0.1 is not compatible with Ruby 3.1+
          - ruby: 3.1
            gemfile: rails_7_0
          - ruby: 3.2
            gemfile: rails_7_0
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}

      - name: Migrate DB
        run: bundle exec rake app:db:migrate

      - name: Prepare DB
        run: bundle exec rake app:db:test:prepare

      - name: Run spec
        run: bundle exec rspec
