name: Test supported versions
on:
  push:
    branches:
      - 'master'
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_8_1.gemfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.4

      - name: Run linters
        run: bin/rubocop

  spec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4', '4.0']
        gemfile: [rails_7_1, rails_7_2, rails_8_0, rails_8_1]
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@v2
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '125.0.6422.141'

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
          rubygems: 3.7.2

      - name: Migrate DB
        run: bin/rake app:db:migrate

      - name: Prepare DB
        run: bin/rake app:db:test:prepare

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Run spec
        run: bin/rspec
